version: '3'
services:
  tegra-api:
    build: .
    environment:
      TZ: "America/Fortaleza"
    volumes:
    - ~/.m2:/home/paulo/.m2
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    ports:
    - 9090:9090
    command: mvn clean spring-boot:run
